server:
  port: 9003
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.118:8888
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.118:3306/db2021?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: '*'